import { makeStyles } from '@mui/styles';
import Head from 'next/head';
import { useEffect } from 'react';
import { useDispatch } from 'react-redux';
import { fetchDataSuccess } from '../redux/DataSlice/dataSlice';

export default function Home() {
    const classes = useStyles();
    const dispatch = useDispatch();

    useEffect(() => {
        console.log('#m distpa: ');
        dispatch(fetchDataSuccess('this id data'));
    });

    return (
        <>
            <Head>
                <title>Destm</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1 className={classes.mainText}>Hello next.js</h1>
            </main>
        </>
    );
}

const useStyles = makeStyles(() => ({
    mainText: {
        color: 'blue',
    },
}));
